module('viewkey', function(tags) {
return function(key) {
	var v = tags.div({},
		tags.div({}, key.name),
		tags.div({ 
			style:
			{
				margin: '0.5em',
				color: '#9FC9C0',
				font: '0.9em sans'
			} }, key.description))
		
	



	return v
}
})

module('index-logic', function(viewkey, tags) {

tags.append(tags.body,
	tags.span({}, 'Auth keys'),
	tags.div({ class: 'button', name: 'newkey' }, 'Generate a new key'),
	viewkey({ name: 'Default Key', description: 'This key has been automatically ' +
		'generated by the extension.' }))
		


})

